// Game Data - Monsters, Weapons, Armors, Level Gains, Masters
// Ported from the original LORD game

export const weapons = [
  { name: 'Stick', cost: 200, attack: 5, strReq: 0 },
  { name: 'Dagger', cost: 1000, attack: 10, strReq: 0 },
  { name: 'Short Sword', cost: 3000, attack: 20, strReq: 15 },
  { name: 'Long Sword', cost: 10000, attack: 30, strReq: 22 },
  { name: 'Huge Axe', cost: 30000, attack: 40, strReq: 32 },
  { name: 'Bone Cruncher', cost: 100000, attack: 60, strReq: 44 },
  { name: 'Twin Swords', cost: 150000, attack: 80, strReq: 64 },
  { name: 'Power Axe', cost: 200000, attack: 120, strReq: 99 },
  { name: "Able's Sword", cost: 400000, attack: 180, strReq: 149 },
  { name: "Wan's Weapon", cost: 1000000, attack: 250, strReq: 224 },
  { name: 'Spear of Gold', cost: 4000000, attack: 350, strReq: 334 },
  { name: 'Crystal Shard', cost: 1000000, attack: 500, strReq: 334 },
  { name: "Nira's Teeth", cost: 40000000, attack: 800, strReq: 334 },
  { name: 'Blood Sword', cost: 100000000, attack: 1200, strReq: 334 },
  { name: 'Death Sword', cost: 400000000, attack: 1800, strReq: 334 }
];

export const armors = [
  { name: 'Coat', cost: 200, defense: 1, strReq: 0 },
  { name: 'Heavy Coat', cost: 1000, defense: 3, strReq: 0 },
  { name: 'Leather Vest', cost: 3000, defense: 10, strReq: 2 },
  { name: 'Bronze Armor', cost: 10000, defense: 15, strReq: 5 },
  { name: 'Iron Armor', cost: 30000, defense: 25, strReq: 10 },
  { name: 'Graphite Armor', cost: 100000, defense: 35, strReq: 20 },
  { name: "Erdrick's Armor", cost: 150000, defense: 50, strReq: 35 },
  { name: 'Armor of Death', cost: 200000, defense: 75, strReq: 57 },
  { name: "Able's Armor", cost: 400000, defense: 100, strReq: 92 },
  { name: 'Full Body Armor', cost: 1000000, defense: 150, strReq: 152 },
  { name: 'Blood Armor', cost: 4000000, defense: 225, strReq: 232 },
  { name: 'Magic Protection', cost: 10000000, defense: 300, strReq: 232 },
  { name: "Belar's Armor", cost: 40000000, defense: 400, strReq: 232 },
  { name: 'Golden Armor', cost: 100000000, defense: 600, strReq: 232 },
  { name: 'Armor of Love', cost: 400000000, defense: 1000, strReq: 232 }
];

export const levelGains = [
  { level: 1, hp: 20, str: 10, def: 1, xpNeeded: 1 },
  { level: 2, hp: 30, str: 15, def: 3, xpNeeded: 100 },
  { level: 3, hp: 45, str: 22, def: 6, xpNeeded: 400 },
  { level: 4, hp: 65, str: 32, def: 11, xpNeeded: 1000 },
  { level: 5, hp: 95, str: 44, def: 21, xpNeeded: 4000 },
  { level: 6, hp: 145, str: 64, def: 36, xpNeeded: 10000 },
  { level: 7, hp: 220, str: 99, def: 58, xpNeeded: 40000 },
  { level: 8, hp: 345, str: 149, def: 93, xpNeeded: 100000 },
  { level: 9, hp: 530, str: 224, def: 153, xpNeeded: 400000 },
  { level: 10, hp: 780, str: 334, def: 233, xpNeeded: 1000000 },
  { level: 11, hp: 1130, str: 484, def: 353, xpNeeded: 4000000 },
  { level: 12, hp: 1680, str: 684, def: 503, xpNeeded: 10000000 }
];

export const masters = [
  { name: 'Halder', hp: 30, str: 15, weapon: 'Short Sword', greeting: "Hi there. Although I may not look muscular, I ain't all that weak. You cannot advance to another Master until you can best me in battle." },
  { name: 'Barak', hp: 50, str: 20, weapon: 'Battle Axe', greeting: "You are now level two, and a respected warrior. Try talking to the Bartender, he will see you now." },
  { name: 'Aragorn', hp: 100, str: 30, weapon: 'Twin Swords', greeting: "You are now level three, and you are actually becoming well known in the realm." },
  { name: 'Olodrin', hp: 120, str: 40, weapon: 'Power Axe', greeting: "You are now level four. But don't get cocky - There are many in the realm that could kick your..." },
  { name: 'Sandtiger', hp: 140, str: 50, weapon: 'Blessed Sword', greeting: "You are now level five..Not bad...Not bad at all.." },
  { name: 'Sparhawk', hp: 160, str: 60, weapon: 'Double Bladed Sword', greeting: "You are level six! Vengeance is yours!" },
  { name: 'Atsuko Sensei', hp: 180, str: 70, weapon: 'Huge Curved Blade', greeting: "Even in my country, you would be considered a good warrior." },
  { name: 'Aladdin', hp: 190, str: 80, weapon: 'Shiny Lamp', greeting: "You are now level eight. Remember, do not use your great strength in bullying the other warriors." },
  { name: 'Prince Caspian', hp: 200, str: 90, weapon: 'Flashing Rapier', greeting: "You are now level nine. You have traveled far on the road of hardships." },
  { name: 'Gandalf', hp: 210, str: 100, weapon: 'Huge Fireballs', greeting: "You are now level ten.. A true honor! You may be the one to rid the realm of the Red Dragon." },
  { name: 'Turgon', hp: 220, str: 120, weapon: "Able's Sword", greeting: "I am Turgon, son. The greatest warrior in the realm. You must find and kill the Red Dragon." }
];

export const monsters = [
  { name: 'Small Thief', weapon: 'Small Dagger', str: 6, hp: 9, gold: 56, xp: 2, death: "You disembowel the little thieving menace!" },
  { name: 'Rude Boy', weapon: 'Cudgel', str: 3, hp: 7, gold: 7, xp: 3, death: "You quietly watch as the very Rude Boy bleeds to death." },
  { name: 'Old Man', weapon: 'Cane', str: 5, hp: 13, gold: 73, xp: 4, death: "You finish him off, by tripping him with his own cane." },
  { name: 'Large Green Rat', weapon: 'Sharp Teeth', str: 3, hp: 4, gold: 32, xp: 1, death: "A well placed step ends this small rodents life." },
  { name: 'Wild Boar', weapon: 'Sharp Tusks', str: 10, hp: 9, gold: 58, xp: 5, death: "You impale the boar between the eyes!" },
  { name: 'Ugly Old Hag', weapon: 'Garlic Breath', str: 6, hp: 9, gold: 109, xp: 4, death: "You emotionally crush the hag, by calling her ugly!" },
  { name: 'Large Mosquito', weapon: 'Blood Sucker', str: 2, hp: 3, gold: 46, xp: 2, death: "With a sharp slap, you end the Mosquitos life." },
  { name: 'Bran The Warrior', weapon: 'Short Sword', str: 12, hp: 15, gold: 234, xp: 10, death: "After a hardy duel, Bran lies at your feet, dead." },
  { name: 'Evil Wretch', weapon: 'Finger Nail', str: 7, hp: 12, gold: 76, xp: 3, death: "With a swift boot to her head, you kill her." },
  { name: 'Small Bear', weapon: 'Claws', str: 9, hp: 7, gold: 154, xp: 6, death: "After a swift battle, you stand holding the Bears heart!" },
  { name: 'Small Troll', weapon: 'Uglyness', str: 6, hp: 14, gold: 87, xp: 5, death: "This battle reminds you how of how much you hate trolls." },
  { name: 'Green Python', weapon: 'Dripping Fangs', str: 13, hp: 17, gold: 80, xp: 6, death: "You tie the mighty snake's carcass to a tree." },
  { name: 'Gath The Barbarian', weapon: 'Huge Spiked Club', str: 12, hp: 13, gold: 134, xp: 9, death: "You knock Gath down, ignoring his constant groaning." },
  { name: 'Evil Wood Nymph', weapon: 'Flirtatious Behavior', str: 15, hp: 10, gold: 160, xp: 11, death: "You shudder to think of what would have happened, had you given in." },
  { name: 'Fedrick The Limping Baboon', weapon: 'Scary Faces', str: 8, hp: 23, gold: 97, xp: 6, death: "Fredrick will never grunt in anyones face again." },
  { name: 'Wild Man', weapon: 'Hands', str: 13, hp: 14, gold: 134, xp: 8, death: "Pitting your wisdom against his brawn has won this battle." },
  { name: 'Brorandia The Viking', weapon: 'Hugely Spiked Mace', str: 21, hp: 18, gold: 330, xp: 20, death: 'You consider this a message to her people, "STAY AWAY!".' },
  { name: 'Huge Bald Man', weapon: 'Glare From Forehead', str: 19, hp: 19, gold: 311, xp: 16, death: "It wasn't even a close battle, you slaughtered him." },
  { name: 'Senile Senior Citizen', weapon: 'Crazy Ravings', str: 13, hp: 11, gold: 270, xp: 13, death: "You may have just knocked some sense into this old man." },
  { name: 'Membrain Man', weapon: 'Strange Ooze', str: 10, hp: 16, gold: 190, xp: 11, death: "The monstrosity has been slain." },
  { name: 'Bent River Dryad', weapon: 'Pouring Waterfall', str: 12, hp: 16, gold: 150, xp: 9, death: 'You cannot resist thinking the Dryad is "All wet".' },
  { name: 'Rock Man', weapon: 'Large Stones', str: 8, hp: 27, gold: 300, xp: 12, death: "You have shattered the Rock Mans head!" },
  { name: 'Lazy Bum', weapon: 'Unwashed Body Odor', str: 19, hp: 29, gold: 380, xp: 18, death: '"This was a bum deal" You think to yourself.' },
  { name: 'Two Headed Rotwieler', weapon: 'Twin Barking', str: 18, hp: 32, gold: 384, xp: 17, death: "You have silenced the mutt, once and for all." },
  { name: 'Purple Monchichi', weapon: 'Continous Whining', str: 14, hp: 29, gold: 763, xp: 23, death: "You cant help but realize you have just killed a real loser." },
  { name: 'Bone', weapon: 'Terrible Smoke Smell', str: 27, hp: 11, gold: 432, xp: 16, death: "Now that you have killed Bone, maybe he will get a life.." },
  { name: 'Red Neck', weapon: 'Awfull Country Slang', str: 19, hp: 16, gold: 563, xp: 19, death: "The dismembered body causes a churning in your stomach." },
  { name: 'Winged Demon Of Death', weapon: 'Red Glare', str: 42, hp: 23, gold: 830, xp: 28, death: "You cut off the Demons head, to be sure of its death." },
  { name: 'Black Owl', weapon: 'Hooked Beak', str: 28, hp: 29, gold: 711, xp: 26, death: "A well placed blow knocks the winged creature to the ground." },
  { name: 'Muscled Midget', weapon: 'Low Punch', str: 26, hp: 19, gold: 870, xp: 32, death: "You laugh as the small man falls to the ground." },
  { name: 'Headbanger Of The West', weapon: 'Ear Shattering Noises', str: 23, hp: 27, gold: 245, xp: 43, death: "You slay the rowdy noise maker and destroy his evil machines." },
  { name: 'Morbid Walker', weapon: 'Endless Walking', str: 28, hp: 10, gold: 764, xp: 9, death: "Even lying dead on its back, it is still walking." },
  { name: 'Magical Evil Gnome', weapon: 'Spell Of Fire', str: 24, hp: 25, gold: 638, xp: 28, death: "The Gnome's small body is covered in a deep red blood." },
  { name: 'Death Dog', weapon: 'Teeth', str: 36, hp: 52, gold: 1150, xp: 36, death: "You rejoice as the dog wimpers for the very last time." },
  { name: 'Weak Orc', weapon: 'Spiked Club', str: 27, hp: 32, gold: 900, xp: 25, death: "A solid blow removes the Orcs head!" },
  { name: 'Dark Elf', weapon: 'Small bow', str: 43, hp: 57, gold: 1070, xp: 33, death: "The Elf falls at your feet, dead." },
  { name: 'Evil Hobbit', weapon: 'Smoking Pipe', str: 35, hp: 95, gold: 1240, xp: 46, death: "The Hobbit will never bother anyone again!" },
  { name: 'Short Goblin', weapon: 'Short Sword', str: 34, hp: 45, gold: 768, xp: 24, death: "A quick lunge renders him dead!" },
  { name: 'Huge Black Bear', weapon: 'Razor Claws', str: 67, hp: 48, gold: 1765, xp: 76, death: "You bearly beat the Huge Bear..." },
  { name: 'Rabid Wolf', weapon: 'Deathlock Fangs', str: 45, hp: 39, gold: 1400, xp: 43, death: "You pull the dogs lifeless body off you." },
  { name: 'Young Wizard', weapon: 'Weak Magic', str: 64, hp: 35, gold: 1754, xp: 64, death: "This Wizard will never cast another spell!" },
  { name: 'Mud Man', weapon: 'Mud Balls', str: 56, hp: 65, gold: 870, xp: 43, death: "You chop up the Mud Man into sushi!" },
  { name: 'Death Jester', weapon: 'Horrible Jokes', str: 34, hp: 46, gold: 1343, xp: 32, death: "You feel no pity for the Jester, his jokes being as bad as they were." },
  { name: 'Pandion Knight', weapon: 'Orkos Broadsword', str: 64, hp: 59, gold: 3100, xp: 98, death: "You are elated in the knowledge that you both fought honorably." },
  { name: 'Jabba', weapon: 'Whiplashing Tail', str: 61, hp: 198, gold: 2384, xp: 137, death: "The fat thing falls down, never to squirm again." },
  { name: 'Manoken Sloth', weapon: 'Dripping Paws', str: 54, hp: 69, gold: 2452, xp: 97, death: "You have cut him down, spraying a nearby tree with blood." },
  { name: 'Trojan Warrior', weapon: 'Twin Swords', str: 73, hp: 87, gold: 3432, xp: 154, death: "You watch, as the ants claim his body." },
  { name: 'Misfit The Ugly', weapon: 'Strange Ideas', str: 75, hp: 89, gold: 2563, xp: 120, death: "You cut him cleanly down the middle, in a masterfull stroke." },
  { name: 'George Of The Jungle', weapon: 'Echoing Screams', str: 56, hp: 43, gold: 2230, xp: 128, death: "You thought the story of George was a myth, until now." },
  { name: 'Silent Death', weapon: 'Pale Smoke', str: 113, hp: 98, gold: 4711, xp: 230, death: "Instead of spilling blood, the creature seems filled with only air." },
  { name: 'Bald Medusa', weapon: 'Glare Of Stone', str: 78, hp: 120, gold: 4000, xp: 256, death: "You are lucky you didnt look at her... Man was she ugly!" },
  { name: 'Black Alligator', weapon: 'Extra Sharp Teeth', str: 65, hp: 65, gold: 3245, xp: 123, death: "With a single stroke, you sever the creatures head right off." },
  { name: 'Clancy, Son Of Emporer Len', weapon: 'Spiked Bull Whip', str: 52, hp: 324, gold: 4764, xp: 324, death: "Its a pity so many new warriors get so proud." },
  { name: 'Black Sorcerer', weapon: 'Spell Of Lightning', str: 86, hp: 25, gold: 2838, xp: 154, death: "Thats the last spell this Sorcerer will ever cast!" },
  { name: 'Iron Warrior', weapon: '3 Iron', str: 100, hp: 253, gold: 6542, xp: 364, death: "You have bent the Iron warriors Iron!" },
  { name: 'Black Soul', weapon: 'Black Candle', str: 112, hp: 432, gold: 5865, xp: 432, death: "You have released the black soul." },
  { name: 'Gold Man', weapon: 'Rock Arm', str: 86, hp: 354, gold: 8964, xp: 493, death: "You kick the body of the Gold man to reveal some change.." },
  { name: 'Screaming Zombie', weapon: 'Gaping Mouth Full Of Teeth', str: 98, hp: 286, gold: 5322, xp: 354, death: "The battle has rendered the zombie even more unatractive then he was." },
  { name: 'Satans Helper', weapon: 'Pack Of Lies', str: 112, hp: 165, gold: 7543, xp: 453, death: "Apparently you have seen through the Devils evil tricks" },
  { name: 'Wild Stallion', weapon: 'Hoofs', str: 78, hp: 245, gold: 4643, xp: 532, death: "You only wish you could have spared the animals life." },
  { name: 'Belar', weapon: 'Fists Of Rage', str: 120, hp: 352, gold: 9432, xp: 565, death: "Not even Belar can stop you!" },
  { name: 'Empty Armour', weapon: 'Cutting Wind', str: 67, hp: 390, gold: 6431, xp: 432, death: "The whole battle leaves you with a strange chill." },
  { name: 'Raging Lion', weapon: 'Teeth And Claws', str: 98, hp: 274, gold: 3643, xp: 365, death: "You rip the jaw bone off the magnificient animal!" },
  { name: 'Huge Stone Warrior', weapon: 'Rock Fist', str: 112, hp: 232, gold: 4942, xp: 543, death: "There is nothing left of the stone warrior, except a few pebbles." },
  { name: 'Emporer Len', weapon: 'Lightning Bull Whip', str: 210, hp: 432, gold: 12043, xp: 764, death: 'His last words were.. "I have failed to avenge my son."' },
  { name: 'Night Hawk', weapon: 'Blood Red Talons', str: 220, hp: 675, gold: 10433, xp: 686, death: "Your last swing pulls the bird out of the air, landing him at your feet" },
  { name: 'Charging Rhinoceros', weapon: 'Rather Large Horn', str: 187, hp: 454, gold: 9853, xp: 654, death: "You finally fell the huge beast, not without a few scratches." },
  { name: 'Goblin Pygmy', weapon: 'Death Squeeze', str: 165, hp: 576, gold: 13252, xp: 754, death: "You laugh at the little Goblin's puny attack." },
  { name: 'Goliath', weapon: 'Six Fingered Fist', str: 243, hp: 343, gold: 14322, xp: 898, death: "Now you know how David felt..." },
  { name: 'Angry Liontaur', weapon: 'Arms And Teeth', str: 187, hp: 495, gold: 13259, xp: 753, death: "You have laid this mythical beast to rest." },
  { name: 'Fallen Angel', weapon: 'Throwing Halos', str: 154, hp: 654, gold: 12339, xp: 483, death: "You slay the Angel, then watch as it gets sucked down into the ground." },
  { name: 'Wicked Wombat', weapon: 'The Dark Wombats Curse', str: 198, hp: 464, gold: 13283, xp: 786, death: "It's hard to believe a little wombat like that could be so much trouble" },
  { name: 'Massive Dinosaur', weapon: 'Gaping Jaws', str: 200, hp: 986, gold: 16753, xp: 1204, death: "The earth shakes as the huge beast falls to the ground." },
  { name: 'Swiss Butcher', weapon: 'Meat Cleaver', str: 230, hp: 453, gold: 8363, xp: 532, death: "You're glad you won...You really didn't want the haircut.." },
  { name: 'Death Gnome', weapon: 'Touch Of Death', str: 270, hp: 232, gold: 10000, xp: 654, death: "You watch as the animals pick away at his flesh." },
  { name: 'Screeching Witch', weapon: 'Spell Of Ice', str: 300, hp: 674, gold: 19753, xp: 2283, death: "You have silenced the witch's infernal screeching." },
  { name: 'Rundorig', weapon: 'Poison Claws', str: 330, hp: 675, gold: 17853, xp: 2748, death: "Rundorig, once your friend, now lays dead before you." },
  { name: 'Wheeler', weapon: 'Annoying Laugh', str: 250, hp: 786, gold: 23433, xp: 1980, death: "You rip the wheeler's wheels clean off!" },
  { name: 'Death Knight', weapon: 'Huge Silver Sword', str: 287, hp: 674, gold: 21923, xp: 4282, death: "The Death knight finally falls, not only wounded, but dead." },
  { name: 'Werewolf', weapon: 'Fangs', str: 230, hp: 543, gold: 19474, xp: 3853, death: "You have slaughtered the Werewolf." },
  { name: 'Fire Ork', weapon: 'FireBall', str: 267, hp: 674, gold: 24933, xp: 3942, death: "You have put out this Fire Orks flame!" },
  { name: 'Wans Beast', weapon: 'Crushing Embrace', str: 193, hp: 1243, gold: 17141, xp: 2432, death: "The hairy thing has finally stopped moving." },
  { name: 'Lord Mathese', weapon: 'Fencing Sword', str: 245, hp: 875, gold: 24935, xp: 2422, death: "You have wiped the sneer off his face once and for all." },
  { name: 'King Vidion', weapon: 'Long Sword Of Death', str: 400, hp: 1243, gold: 28575, xp: 6764, death: "You feel lucky to have lived, things could have gone sour.." },
  { name: 'Baby Dragon', weapon: 'Dragon Smoke', str: 176, hp: 2322, gold: 25863, xp: 3675, death: "This Baby Dragon will never grow up." },
  { name: 'Pink Elephant', weapon: 'Stomping', str: 434, hp: 1232, gold: 33844, xp: 7843, death: "You have witnessed the Pink Elephant...And you aren't even drunk!" },
  { name: "Gwendolens Nightmare", weapon: 'Dreams', str: 490, hp: 764, gold: 35846, xp: 8232, death: "This is the first Nightmare you have put to sleep." },
  { name: 'Flying Cobra', weapon: 'Poison Fangs', str: 400, hp: 1123, gold: 37694, xp: 8433, death: "The creature falls to the ground with a sickening thud." },
  { name: "Rentakis Pet", weapon: 'Gaping Maw', str: 556, hp: 987, gold: 37584, xp: 9854, death: "You vow to find Rentaki and tell him what you think about his new pet." },
  { name: 'Ernest Brown', weapon: 'Knee', str: 432, hp: 2488, gold: 34833, xp: 9754, death: "Ernest has finally learned his lesson it seems." },
  { name: 'Scallian Rap', weapon: 'Way Of Hurting People', str: 601, hp: 788, gold: 22430, xp: 6784, death: "Scallians dead...Looks like you took out the trash..." },
  { name: 'Apeman', weapon: 'Hairy Hands', str: 498, hp: 1283, gold: 38955, xp: 7202, death: "The battle is over...Nothing is left but blood and hair." },
  { name: 'Hemo-Glob', weapon: 'Weak Insults', str: 212, hp: 1232, gold: 27853, xp: 4432, death: "The battle is over.. And you really didn't find him particularly scary." },
  { name: 'FrankenMoose', weapon: 'Butting Head', str: 455, hp: 1221, gold: 31221, xp: 5433, death: "That Moose was a perversion of nature!" },
  { name: 'Earth Shaker', weapon: 'Earthquake', str: 767, hp: 985, gold: 37565, xp: 7432, death: "The battle is over...And it looks like you shook him up..." },
  { name: "Gollums Wrath", weapon: 'Ring Of Invisibility', str: 621, hp: 2344, gold: 42533, xp: 13544, death: "Gollums ring apparently wasn't powerfull enough." },
  { name: 'Toraks Son, Korak', weapon: 'Sword Of Lightning', str: 921, hp: 1384, gold: 46575, xp: 13877, death: "You have slain the son of a God! You ARE great!" },
  { name: 'Brand The Wanderer', weapon: 'Fighting Quarter Staff', str: 643, hp: 2788, gold: 38755, xp: 13744, death: "Brand will wander no more." },
  { name: 'The Grimest Reaper', weapon: 'White Sickle', str: 878, hp: 1674, gold: 39844, xp: 14237, death: "You have killed that which was already dead. Odd." },
  { name: 'Death Dealer', weapon: 'Stare Of Paralization', str: 765, hp: 1764, gold: 47333, xp: 13877, death: "The Death Dealer has been delt his last hand." },
  { name: 'Tiger Of The Deep Jungle', weapon: 'Eye Of The Tiger', str: 587, hp: 3101, gold: 43933, xp: 9766, death: "The Tiger's cubs weep over their dead mother." },
  { name: 'Sweet Looking Little Girl', weapon: 'Demon Strike', str: 989, hp: 1232, gold: 52322, xp: 14534, death: "If it wasn't for her manners, you might have got along with her." },
  { name: 'Floating Evil Eye', weapon: 'Evil Stare', str: 776, hp: 2232, gold: 43233, xp: 13455, death: "You really didn't like the look of that Eye..." },
  { name: 'Slock', weapon: 'Swamp Slime', str: 744, hp: 1675, gold: 56444, xp: 14333, death: "Walking away from the battle, you nearly slip on the thing's slime." },
  { name: 'Adult Gold Dragon', weapon: 'Dragon Fire', str: 565, hp: 3222, gold: 56444, xp: 15364, death: "He was strong, but you were stronger." },
  { name: 'Kill Joy', weapon: 'Terrible Stench', str: 988, hp: 3222, gold: 168844, xp: 25766, death: "Kill Joy has fallen, and can't get up." },
  { name: 'Gorma The Leper', weapon: 'Contagous Desease', str: 1132, hp: 2766, gold: 168774, xp: 26333, death: "It looks like the lepers fighting stratagy has fallen apart.." },
  { name: 'Shogun Warrior', weapon: 'Japanese Nortaki', str: 1143, hp: 3878, gold: 165433, xp: 26555, death: "He was tough, but not nearly tough enough." },
  { name: 'Apparently Weak Old Woman', weapon: '*GODS HAMMER*', str: 1543, hp: 1878, gold: 173522, xp: 37762, death: "You pull back the old womans hood, to reveal an eyeless skull." },
  { name: "Ables Creature", weapon: 'Bear Hug', str: 985, hp: 2455, gold: 176775, xp: 28222, death: "That was a mighty creature. Created by a mighty man." },
  { name: 'White Bear Of Lore', weapon: 'Snow Of Death', str: 1344, hp: 1875, gold: 65544, xp: 16775, death: "The White Bear Of Lore DOES exist you've found. Too bad it's now dead." },
  { name: 'Mountain', weapon: 'Landslide', str: 1544, hp: 1284, gold: 186454, xp: 38774, death: "You have knocked the mountain to the ground. Now it IS the ground." },
  { name: 'Sheena The Shapechanger', weapon: 'Deadly Illusions', str: 1463, hp: 1898, gold: 165755, xp: 26655, death: "Sheena is now a quivering mass of flesh. Her last shapechange." },
  { name: 'ShadowStormWarrior', weapon: 'Mystical Storm', str: 1655, hp: 2767, gold: 162445, xp: 26181, death: "The storm is over, and the sunshine greets you as the victor." },
  { name: 'Madman', weapon: 'Chant Of Insanity', str: 1265, hp: 1764, gold: 149564, xp: 25665, death: "Madman must have been mad to think he could beat you!" },
  { name: 'Vegetable Creature', weapon: 'Pickled Cabbage', str: 111, hp: 172, gold: 4838, xp: 2187, death: "For once you finished off your greens..." },
  { name: 'Cyclops Warrior', weapon: 'Fire Eye', str: 1744, hp: 2899, gold: 204000, xp: 49299, death: "The dead Cyclop's one eye stares at you blank." },
  { name: 'Corinthian Giant', weapon: 'De-rooted Tree', str: 2400, hp: 2544, gold: 336643, xp: 60333, death: "You hope the giant has brothers, more sport for you." },
  { name: 'The Screaming Eunuch', weapon: 'High Pitched Voice', str: 1488, hp: 2877, gold: 197888, xp: 78884, death: "If it wasn't for his ugly features, you thought he looked female." },
  { name: 'Black Warlock', weapon: 'Satanic Choruses', str: 1366, hp: 2767, gold: 168483, xp: 58989, death: "You have slain Satan's only son." },
  { name: 'Kal Torak', weapon: 'Cthrek Goru', str: 876, hp: 6666, gold: 447774, xp: 94663, death: "You have slain a God! You ARE great!" },
  { name: 'The Mighty Shadow', weapon: 'Shadow Axe', str: 1633, hp: 2332, gold: 176333, xp: 51655, death: "The mighty Shadow is now only a Shadow of his former self." },
  { name: 'Black Unicorn', weapon: 'Shredding Horn', str: 1899, hp: 1587, gold: 336693, xp: 41738, death: "You have felled the Unicorn." },
  { name: 'Mutated Black Widow', weapon: 'Venom Bite', str: 2575, hp: 1276, gold: 434370, xp: 98993, death: "A well placed stomp ends this Spider's life." },
  { name: 'Humongous Black Wyre', weapon: 'Death Talons', str: 1166, hp: 3453, gold: 653834, xp: 76000, death: "The Wyre's dead carcass covers the whole field!" },
  { name: 'The Wizard Of Darkness', weapon: 'Chant Of Insanity', str: 1497, hp: 1383, gold: 224964, xp: 39878, death: "This Wizard of Darkness will never bother you again" },
  { name: 'Great Ogre Of The North', weapon: 'Spiked Steel Mace', str: 1800, hp: 2878, gold: 524838, xp: 112833, death: 'No one is going to call him The "Great" Ogre Of The North again.' }
];

export const deathMessages = [
  '"Damn, Damn, Damn!", roars.',
  '"I would rather gargle razor blades then be beaten by you!" screams.',
  '"How the hell did you do that?!" shouts.',
  '"You got lucky!" declares.',
  '"Try that again! I\'ll decapitate you!" challenges.',
  '"You are definatly stronger than you look." admits.',
  '"I am SO mad I could slice you in two!" screams.',
  '"You have not seen the last of me!" threatens.',
  '"How could a scrawny little wimp like this best me?" wonders aloud.',
  '"How many of you live in that forest anyway?" ponders.',
  '"Ack! I was under the impression I was invincible." admits.',
  '"Killed by. I am disgraced." grieves.',
  '"I\'LL BE BACK!" swears.',
  '"At least I wasn\'t bested by a Large Rat, eh?" shrugs.',
  '"My goodness. This a turn for the worse." states.',
  '"You never think it can happen to you...Then WHAM!" explains.',
  '"I think I\'m going to be sick." moans pitifully.',
  '"I feel ill." elucidates.',
  '"Well...So much for my reputation!" expounds.',
  '"Damnit! I was looking for the Dark Cloak Tavern." explains in dismay.'
];

export const classNames = ['Warrior', 'Death Knight', 'Mystic', 'Thief'];

export const defaultPlayer = {
  name: '',
  irc_nick: '',
  class: 0,
  sex: 0,
  level: 1,
  hp: 20,
  maxhp: 20,
  str: 10,
  def: 1,
  weapon_num: 1,
  armor_num: 1,
  gold: 6000,
  bank: 0,
  gems: 0,
  xp: 1,
  fights: 500,
  pfights: 3,
  pfights_timer: 0,
  dead: 0,
  charm: 1,
  horse: 0,
  lays: 0,
  marriedto: '',
  fairies: 0,
  seen_master: 0,
  seen_dragon: 0,
  seenviolet: 0,
  flirted: 0,
  stayinn: 0,
  classd: 1,
  classm: 0,
  classt: 0,
  usesd: 1,
  usesm: 0,
  usest: 0,
  skill_charges_max: 0,
  skill_charges_active: 0,
  skill_charge_timers: [],
  mastered: -1,
  mastered2: -1,
  mastered3: -1,
  baraks_visited_today: 0,
  killed_by: '',
  skill_reset_timer: 0,
  seenbard: 0,
  violet_timer: 0
};

export const forestEvents = [
  {
    name: 'Treasure Chest',
    chance: 5,
    message: 'You stumble upon a hidden treasure chest!',
    type: 'treasure'
  },
  {
    name: 'Bandit Ambush',
    chance: 10,
    message: 'A bandit leaps out from behind a tree!',
    type: 'bandit'
  },
  {
    name: 'Healing Fairy',
    chance: 8,
    message: 'A glowing fairy appears and sprinkles magic dust on you!',
    type: 'fairy'
  },
  {
    name: 'Strange Noise',
    chance: 5,
    message: 'You hear strange noises in the distance... but nothing happens.',
    type: 'nothing'
  },
  {
    name: 'Wandering Merchant',
    chance: 5,
    message: 'A mysterious merchant approaches you with wares to sell.',
    type: 'merchant'
  },
  {
    name: 'Ancient Ruins',
    chance: 3,
    message: 'You discover ancient ruins with strange inscriptions...',
    type: 'ruins'
  },
  {
    name: 'Snow Storm',
    chance: 5,
    message: 'A sudden snow storm chills you to the bone!',
    type: 'snow'
  },
  {
    name: 'Vampire Bat Swarm',
    chance: 8,
    message: 'A swarm of vampire bats attacks you!',
    type: 'bats'
  },
  {
    name: 'Mysterious Herbs',
    chance: 6,
    message: 'You find some mysterious herbs growing nearby.',
    type: 'herbs'
  },
  {
    name: 'Lost Traveler',
    chance: 5,
    message: 'A lost traveler asks for directions. In gratitude, they give you some gold.',
    type: 'traveler'
  },
  {
    name: 'Dwarf Games',
    chance: 5,
    message: 'A sly looking dwarf hops out of the brush! "How about a game, friend?"',
    type: 'dwarf'
  },
  {
    name: 'Forest Hut',
    chance: 3,
    message: 'While trekking through the forest, you come upon a small hut.',
    type: 'hut'
  },
  {
    name: 'Wierd Event',
    chance: 2,
    message: 'You hear the voice of angels singing.',
    type: 'wierd'
  },
  {
    name: 'Old Man',
    chance: 5,
    message: 'You come across an old man who seems lost.',
    type: 'oldman'
  },
  {
    name: 'Scroll',
    chance: 5,
    message: 'You stumble upon a dead bird with a scroll.',
    type: 'scroll'
  },
  {
    name: 'Old Hag',
    chance: 3,
    message: 'You come across an ugly old hag.',
    type: 'hag'
  },
  {
    name: 'Hammer Stone',
    chance: 2,
    message: 'You find a Hammer Stone!',
    type: 'hammer'
  },
  {
    name: 'Dark Cloak Tavern',
    chance: 2,
    message: 'Through the trees, you spot a faint light...',
    type: 'darkcloak'
  }
];
